# Generated by Django 5.1.5 on 2025-01-19 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_products_razmer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='yulduz',
        ),
    ]
