# Generated by Django 5.1.5 on 2025-01-21 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_categorysale_products_category2'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='category1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.categorysale'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.categorygander'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='category2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoryproduct'),
        ),
    ]
