# Generated by Django 5.1.5 on 2025-01-21 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_categoryproduct_products_category1_products_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.categoryproduct'),
        ),
    ]
