# Generated by Django 5.1.5 on 2025-01-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_categoryproduct_slug_alter_categorysale_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
