# Generated by Django 5.1.5 on 2025-01-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_products_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoryRang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='categoryRazmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1)),
                ('slug', models.SlugField(max_length=1, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='razmer',
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='products',
            name='rang',
            field=models.ManyToManyField(to='app.categoryrang'),
        ),
        migrations.AddField(
            model_name='products',
            name='razmer',
            field=models.ManyToManyField(to='app.categoryrazmer'),
        ),
    ]
