# Generated by Django 5.1.5 on 2025-01-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_categoryrang_categoryrazmer_remove_products_razmer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
