# Generated by Django 5.1.5 on 2025-01-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_products_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('rasm', models.ImageField(upload_to='likes/')),
                ('slug', models.SlugField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('rezmer', models.CharField(max_length=50)),
                ('narx', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='rasm',
            field=models.ImageField(help_text="Hurmatli admin rasm jo'natayotganingizda rasm 800x600 razmerida bo'lsin", upload_to='product'),
        ),
    ]
