# Generated by Django 5.1.5 on 2025-01-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_like_alter_products_rasm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='rezmer',
        ),
        migrations.AlterField(
            model_name='like',
            name='narx',
            field=models.CharField(max_length=255),
        ),
    ]
