# Generated by Django 5.1.5 on 2025-01-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_like_rezmer_alter_like_narx'),
    ]

    operations = [
        migrations.CreateModel(
            name='bascet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('rasm', models.ImageField(upload_to='bascet/')),
                ('title', models.CharField(max_length=255)),
                ('rang', models.CharField(max_length=50)),
                ('razmer', models.CharField(max_length=5)),
                ('narx', models.PositiveBigIntegerField()),
                ('soni', models.PositiveIntegerField()),
            ],
        ),
    ]
