# Generated by Django 5.1.5 on 2025-01-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_bascet'),
    ]

    operations = [
        migrations.AddField(
            model_name='bascet',
            name='jami',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
