# Generated by Django 5.1.5 on 2025-01-29 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_bascet_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='zay_first',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('pre_title', models.CharField(max_length=35)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='zay_firs/')),
            ],
        ),
        migrations.CreateModel(
            name='category_month_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='month_category/')),
                ('title', models.CharField(max_length=15)),
                ('slug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoryproduct')),
            ],
        ),
        migrations.CreateModel(
            name='catagorys_of_month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=100)),
                ('imgs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category_month_img')),
            ],
        ),
    ]
