# Generated by Django 5.1.5 on 2025-01-29 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_catagorys_of_month_imgs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_month_img',
            old_name='slug',
            new_name='other',
        ),
        migrations.RemoveField(
            model_name='category_month_img',
            name='title',
        ),
    ]
