# Generated by Django 5.1.5 on 2025-01-29 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_slug_category_month_img_other_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='catagorys_of_month',
            new_name='zay_second',
        ),
    ]
