# Generated by Django 5.1.5 on 2025-01-30 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_catagorys_of_month_zay_second'),
    ]

    operations = [
        migrations.CreateModel(
            name='zay_second_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='zay_second',
            name='description',
        ),
        migrations.RemoveField(
            model_name='zay_second',
            name='title',
        ),
        migrations.AddField(
            model_name='zay_second',
            name='img',
            field=models.ImageField(default=1, upload_to='month_category/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zay_second',
            name='other',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.categoryproduct'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='category_month_img',
        ),
    ]
