# Generated by Django 5.1.5 on 2025-01-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_zay_second_text_remove_zay_second_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zay_second',
            name='img',
            field=models.ImageField(upload_to='zay_second/'),
        ),
    ]
