# Generated by Django 5.1.5 on 2025-01-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_zay_second_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='zat_third',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('pre_title', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='zay_third/')),
                ('price', models.PositiveBigIntegerField()),
                ('pro_title', models.CharField(max_length=15)),
                ('pro_pre_title', models.CharField(max_length=100)),
            ],
        ),
    ]
