# Generated by Django 5.1.5 on 2025-01-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_zat_third'),
    ]

    operations = [
        migrations.CreateModel(
            name='zay_third',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='zay_third/')),
                ('price', models.PositiveBigIntegerField()),
                ('title', models.CharField(max_length=15)),
                ('pre_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='zay_third_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('pre_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='zat_third',
        ),
    ]
